<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>FanControl.Stm32FanCdc</AssemblyName>
    <RootNamespace>FanControl.Stm32FanCdc</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="FanControl.Plugins">
      <HintPath>C:\Program Files (x86)\FanControl\FanControl.Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="System.IO.Ports">
      <HintPath>C:\Program Files (x86)\FanControl\System.IO.Ports.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
